{
 "title": "Zeitgeist Node Monitor",
 "description": "Zeitgeist Node Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Basic Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zeitgeist Node Monitor",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://zeitgeist.pm/Moon_White.png\" style=\"zoom:10%;\" />"
   }
  },
  {
   "title": "Block Height of Zeitgeist",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_block_height", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Zeitgeist Node Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_process_start_time_seconds",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Zeitgeist Node Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "substrate_tokio_threads_alive", "legendFormat": "Zeitgeist Alive Thread" },
    { "expr": "substrate_tokio_threads_total", "legendFormat": "Zeitgeist Total Thread" }
   ]
  },
  {
   "title": "Node Infos",
   "type": "logs",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "targets": [
    { "expr": "substrate_build_info", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Transactions In The Ready Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of Connected Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_sync_peers", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Number of Known Chain Forks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_number_leaves", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Network Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "libp2p Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections_opened_total",
     "legendFormat": "Opened connections for {{direction}}"
    },
    {
     "expr": "substrate_sub_libp2p_connections_closed_total",
     "legendFormat": "Closed connections for {{direction}}"
    },
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_closed_total",
     "legendFormat": "Closed connections for distinct peers"
    },
    {
     "expr": "substrate_sub_libp2p_distinct_peers_connections_opened_total",
     "legendFormat": "Opened connections for distinct peers"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Peers count"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "substrate_sub_libp2p_peerset_num_requested",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "libp2p Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_listeners_errors_total",
     "legendFormat": "libp2p listeners errors"
    },
    {
     "expr": "substrate_sub_libp2p_pending_connections_errors_total",
     "legendFormat": "libp2p pending connections errors"
    }
   ]
  },
  {
   "title": "Requests Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "substrate_parachain_chain_api_requests_total",
     "legendFormat": "Parachain API requests"
    },
    {
     "expr": "substrate_issued_light_requests",
     "legendFormat": "Issued light client requests"
    },
    {
     "expr": "substrate_parachain_runtime_api_make_runtime_api_request_count",
     "legendFormat": "Parachain runtime API requests"
    },
    {
     "expr": "substrate_parachain_runtime_api_requests_total",
     "legendFormat": "{{success}} runtime API requests"
    }
   ]
  },
  {
   "title": "Txpool Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "substrate_sub_txpool_block_transactions_pruned",
     "legendFormat": "Pruned Transaction"
    },
    {
     "expr": "substrate_sub_txpool_block_transactions_resubmitted",
     "legendFormat": "Resubmitted Transaction"
    },
    {
     "expr": "substrate_sub_txpool_submitted_transactions",
     "legendFormat": "Submitted Transaction"
    },
    {
     "expr": "substrate_sub_txpool_validations_finished",
     "legendFormat": "Finished Validation"
    },
    {
     "expr": "substrate_sub_txpool_validations_invalid",
     "legendFormat": "Invalid Validation"
    },
    {
     "expr": "substrate_sub_txpool_validations_scheduled",
     "legendFormat": "Scheduled Validation"
    }
   ]
  },
  {
   "title": "Tasks Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total[1m]) - rate(substrate_tasks_polling_duration_count[1m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  { "title": "Storage Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "State Cache DB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_state_db_cache_bytes", "legendFormat": "{{subtype}}" }
   ]
  },
  {
   "title": "State Cache",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes" }
   ]
  },
  {
   "title": "RocksDB Cache",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_database_cache_bytes" }
   ]
  }
 ]
}